xcversion(version: "10.1") 
xcode_select "/Applications/Xcode.app"
default_platform(:ios)
generated_fastfile_id "4303a121-f78f-4d6e-bb25-8c35c502949c"

platform :ios do
  desc "Description of what the lane does"
 
 lane :beta do
  # build your iOS app
  build_app(
    scheme: "JenkensTest",
    export_method: "ad-hoc"
  )

  # upload to Testflight
   crashlytics(
    api_token: "f4f66007d3a682ab7a6ecb4cd66aeacc886be80b",
    build_secret: "e38d42eda67f4cedde95f0e2577e939dc2e8cefed98c1999bdc5290f045c6c37"
  )

  build_app(
    scheme: "JenkensTest",
    export_method: "app-store"
  )

  pilot(skip_waiting_for_build_processing: true)
end

  lane :generate_ipa_develop do
    build_ios_app(
      configuration: "Release",
      scheme: "JenkensTest",
      clean: true,
      export_method: 'ad-hoc',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: Time.now.strftime("%d/%m/%Y %H:%M").
concat(".ipa"),
    )
  end
  after_all do |lane|
 #lane :slack_message do
      slack(
          message: "App successfully uploaded to iTunesConnect.",
          success: true,
          slack_url: "https://hooks.slack.com/services/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"
      )
  end
  lane :mail_message do
      mailgun(
      to: "magdy.kamal@apptcom.com",
      success: true,
      message: "This is the mail's content"
      )
  end
  
end