xcversion(version: "10.1") 
xcode_select "/Applications/Xcode.app"
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
 
  lane :generate_ipa_develop do
    build_ios_app(
      configuration: "Release",
      scheme: "JenkensTest",
      clean: true,
      export_method: 'ad-hoc',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: Time.now.strftime("%d/%m/%Y %H:%M").
concat(".ipa"),
    )
  end
  lane :slack_message do
      slack(
          message: "App successfully uploaded to iTunesConnect.",
          success: true,
          slack_url: "https://hooks.slack.com/services/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"
      )
  end
end